### ISSUE TITLE
Issues running under AWS ELB

### ISSUE THREAD

**Issue by matthewford** [haraka/haraka-plugin-watch#2]
Ideally I would like my http traffic to go over port 80, and the websocket traffic to port 443 so I can use AWS ELB tcp protocol which supports websockets.

**Comment by msimerson** [comment]
Have you tested it?  IIRC, you must do both HTTP and WebSockets over the same protocol and port. Either do both (http + ws) over port 80 or both (https + wss) on port 443.

**Comment by matthewford** [comment]
@msimerson no didnt manage to our git fork running, ran into an issue with running `node haraka.js`, then also had issues trying to run the binary in the git repo. 

> you must do both HTTP and WebSockets over the same protocol and port

Really? 😢  How would you do this on AWS using Elastic Load Balancers, as the protocols that do HTTP load balancing do not support Websockets (and tpc will not load the webpage).

Would you front haraka with something like Nginx?

**Comment by msimerson** [comment]
I use nginx/lighttpd/apache interchangeably and I rarely configure any of the trio for https. It's simpler and easier to terminate all of the connections with haproxy ([as shown here]( https://github.com/msimerson/Mail-Toaster-6/blob/master/provision-haproxy.sh#L49-L63)) and then proxy the HTTP (or TCP) requests to the backend server(s).

**Comment by msimerson** [comment]
closing, since this is a "feature" of WS and there's nothing that `watch` can do about it.
